- scalar
- vector
- matrix
- n-dimensional tensor

In [1]:
import torch
from torch import tensor

Scalar
通常是一个数值

In [2]:
x = tensor(42.)
x

tensor(42.)

In [3]:
x.dim()

0

In [4]:
2 * x

tensor(84.)

In [5]:
x.item()

42.0

Vector
例如：[-5, -2, -1]，在深度学习中通常指特征，例如词向量特征，某一维度特征等 $\overrightarrow{v}={\{v_1, v_2, ..., v_n\}}$

In [6]:
v = tensor([1.5, -0.5, 3.0])
v

tensor([ 1.5000, -0.5000,  3.0000])

In [8]:
v.dim()

1

In [9]:
v.size()

torch.Size([3])

Matrix
- 一般计算的都是矩阵，通常是多维的

In [10]:
M = tensor([[1., 2.], [3., 4.]])
M

tensor([[1., 2.],
        [3., 4.]])

In [12]:
M.matmul(M)

tensor([[ 7., 10.],
        [15., 22.]])

In [13]:
tensor([1., 0.]).matmul(M)

tensor([1., 2.])

In [14]:
M * M

tensor([[ 1.,  4.],
        [ 9., 16.]])

![](images/n-dim-tensor.png)