In [17]:
import torch

x = torch.empty(5, 3)
print(x)

x = torch.zeros(5, 3, dtype=torch.long)
print(x)

x = torch.tensor([5.5, 3])
print(x)

x = x.new_ones(5, 3, dtype=torch.double)
print(x)


tensor([[1.0653e-38, 1.0194e-38, 4.6838e-39],
        [8.4489e-39, 9.6429e-39, 8.4490e-39],
        [9.6429e-39, 9.2755e-39, 1.0286e-38],
        [9.0919e-39, 8.9082e-39, 9.2755e-39],
        [8.4490e-39, 9.2755e-39, 1.0561e-38]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [3]:
x = torch.rand_like(x, dtype=torch.float)
print(x)

print(x.size())

y = torch.rand(5, 3)
print(x + y)
print(torch.add(x, y))

print(x[:, 1])

tensor([[0.8508, 0.9738, 0.0919],
        [0.9552, 0.1984, 0.4529],
        [0.5337, 0.3116, 0.1141],
        [0.6034, 0.3606, 0.2269],
        [0.0252, 0.5468, 0.6703]])
torch.Size([5, 3])
tensor([[1.0209, 1.6176, 0.3622],
        [1.0623, 0.9106, 0.6414],
        [1.1648, 0.3173, 0.8764],
        [0.9040, 0.6648, 0.7751],
        [0.3328, 1.4095, 0.8451]])
tensor([[1.0209, 1.6176, 0.3622],
        [1.0623, 0.9106, 0.6414],
        [1.1648, 0.3173, 0.8764],
        [0.9040, 0.6648, 0.7751],
        [0.3328, 1.4095, 0.8451]])
tensor([0.9738, 0.1984, 0.3116, 0.3606, 0.5468])


view 操作可以改变矩阵维度

In [8]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # -1 表示第一个维度自行计算得到
print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[-0.7472,  0.2616, -2.1538, -0.4864],
        [ 1.4635,  1.1450, -0.7236,  1.3751],
        [-0.9010,  0.1118, -0.8604,  0.1466],
        [ 0.4066, -0.3960, -0.1872, -0.3290]])
tensor([-0.7472,  0.2616, -2.1538, -0.4864,  1.4635,  1.1450, -0.7236,  1.3751,
        -0.9010,  0.1118, -0.8604,  0.1466,  0.4066, -0.3960, -0.1872, -0.3290])
tensor([[-0.7472,  0.2616, -2.1538, -0.4864,  1.4635,  1.1450, -0.7236,  1.3751],
        [-0.9010,  0.1118, -0.8604,  0.1466,  0.4066, -0.3960, -0.1872, -0.3290]])


与 Numpy 协同操作

In [11]:
a = torch.ones(5)

b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [16]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)